INSERT INTO BOOK VALUES (1, 'Sapiens');
INSERT INTO BOOK VALUES (2, 'Homo Deus');
INSERT INTO BOOK VALUES (3, 'SAND STORM');
INSERT INTO BOOK VALUES (4, 'A ARTE DA GUERRA');
INSERT INTO BOOK VALUES (5, 'O Poder do Infinito');